#!/bin/ksh
set -e

. ./feedcrack.conf

function usage {
	echo 'usage: ${0##*/} <ABSOLUTE PATH bitstring file> <plain text frame number>'
        exit 1
}

[[ -z $2 ]] && usage

bitstreamfile=$1
frame=$2

./feedemptyframe $bitstreamfile $frame
echo

cd $krakenpath/
./kraken ../indexes < $bitstreamfile.$frame.emptyframe234
echo

