#!/bin/bash
set -e

. ./feedcrack.conf

[[ -z $2 ]] && echo BITSTRING FILE AND PLAIN-TEXT FRAME NUMBER? && exit 1

file=$1
frame=$2

[[ ! -f $file ]] && echo file $file not found && exit 1
[[ ! -f $utilspath/xor.py ]] && echo file $utilspath/xor.py not found && exit 1

#./getemptyframeplain $file $frame
#./getemptyframecipher $file $frame

#is there a faster way to feed the array?
i=0
for burst in `cut -f3 -d' ' /root/capture/crackidleplain`; do
	plainburst[$i]=$burst
	(( i += 1 ))
	echo $i
done
unset burst i

echo preparing /root/capture/crackidlexors1234
i=0
for burst in `cut -f3 -d' ' /root/capture/crackidlecipher`; do
	python $utilspath/xor.py ${plainburst[$i]} $burst
	(( i += 1 ))
	(( i == 4 )) && (( i = 0 ))
done > /root/capture/crackidlexors1234 && true
unset burst i

echo preparing /root/capture/crackidlexors
i=0
for xor in `cat /root/capture/crackidlexors1234`; do
	(( i == 0 )) || echo crack $xor
	(( i += 1 ))
	(( i == 4 )) && (( i = 0 ))
done > /root/capture/crackidlexors && true
unset xor i

wc -l /root/capture/crackidlexors1234
wc -l /root/capture/crackidlexors
echo all done

