#!/bin/bash
set -e

. ./feedcrack.conf

[[ -z $2 ]] && echo BITSTRING FILE AND PLAIN-TEXT FRAME NUMBER? && exit 1
[[ ! -f $utilspath/xor.py ]] && echo file $utilspath/xor.py not found && exit 1

#./getburstsplain $file $frame
#./getburstscipher $file $frame

#is there a faster way to feed the array?
echo feeding the plain-text array...
i=0
for burst in `cat /root/capture/si5`; do
	plainburst[$i]=$burst
	i=$(( i += 1 ))
done && echo done
unset burst i

#TODO check C1 C0 C0 C0 cipherbursts
echo -n writing to /root/capture/xors1234 ...
i=0
for burst in `cat /root/capture/si5.guessed`; do
	python $utilspath/xor.py ${plainburst[$i]} $burst
	i=$(( i += 1 ))
	(( i == 4 )) && i=0
done > /root/capture/xors1234 && echo done
unset burst i

#prepare stdin for Kraken
#we want anything but the first burst
echo -n writing to /root/capture/crackxors ...
i=0
for xor in `cat /root/capture/xors1234`; do
	(( i == 0 )) || echo crack $xor
	i=$(( i += 1 ))
	(( i == 4 )) && i=0
done > /root/capture/crackxors && echo done
unset xor i

wc -l /root/capture/si5
wc -l /root/capture/si5.guessed
wc -l /root/capture/xors1234
wc -l /root/capture/crackxors

