#!/bin/bash
set -e

. ./feedcrack.conf

[[ -z $2 ]] && echo SI56 BITSTRING FILE AND PLAINFRAME? && exit 1

file=$1
frame=$2

sequence=`echo $(($frame + 102)) $(($frame + 204)) $(($frame + 306)) $(($frame + 408))`
unset frame

echo -n processing frames $sequence ...
for frame in $sequence; do
	burst2=$(( $frame + 1 ))
	burst3=$(( $frame + 2 ))
	burst4=$(( $frame + 3 ))
	grep "^C1 $frame "  $file
	grep "^C0 $burst2 " $file
	grep "^C0 $burst3 " $file
	grep "^C0 $burst4 " $file
	unset burst2 burst3 burst4
done > /root/capture/crackplain && echo done
unset frame

