#!/bin/bash

. ./feedcrack.lib.bash

[[ -z $2 ]] && usage

file=$1
frame=$2

sequence=`echo $(($frame + 102)) $(($frame + 204)) $(($frame + 306)) $(($frame + 408))`
unset frame

for frame in $sequence; do
	burst2=$(( $frame + 1 ))
	burst3=$(( $frame + 2 ))
	burst4=$(( $frame + 3 ))
	grep "^C1 $frame "  $file
	grep "^C0 $burst2 " $file
	grep "^C0 $burst3 " $file
	grep "^C0 $burst4 " $file
	unset burst2 burst3 burst4
done > $file.$frame.cipher && echo $file.$frame.cipher; unset frame

