#!/bin/bash

. ./feedcrack.conf

usage() {
        echo 'usage: ${0##*/} <bitstring file> <plain text frame number>'
        exit 1
}

[[ -z $2 ]] && usage

file=$1
frame=$2

#sequence=`echo $(($frame + 357))`
sequence=`echo $(($frame + 51)) $(($frame + 102)) $(($frame + 153)) $(($frame + 204)) $(($frame + 255)) $(($frame + 306)) $(($frame + 357)) $(($frame + 408)) $(($frame + 459)) $(($frame + 510)) $(($frame + 561)) $(($frame + 612))`
#x6 x7 ...
#sequence=`echo $(($frame + 306)) $(($frame + 357)) $(($frame + 408)) $(($frame + 459)) $(($frame + 510)) $(($frame + 561))`

echo working on frame numbers $sequence
for burst in $sequence; do
	burst2=$(( $burst + 1 ))
	burst3=$(( $burst + 2 ))
	burst4=$(( $burst + 3 ))
	grep "$burst "  $file
	grep "$burst2 " $file
	grep "$burst3 " $file
	grep "$burst4 " $file
	unset burst2 burst3 burst4
done > $file.$frame.emptyframecipher && echo $file.$frame.emptyframecipher; unset burst

