#!/bin/bash

. ./feedcrack.conf

[[ -z $2 ]] && echo BITSTRING FILE AND PLAIN-TEXT FRAME NUMBER? && exit 1

file=$1
frame=$2

burst() {
	burst2=$(( $frame + 1 ))
	burst3=$(( $frame + 2 ))
	burst4=$(( $frame + 3 ))
	grep "^$frame "  $file
	grep "^$burst2 " $file
	grep "^$burst3 " $file
	grep "^$burst4 " $file
	unset burst2 burst3 burst4
}

echo -n writing frame $frame burst bitstrings to $file.$frame.emptyframeplain ...
burst > $file.$frame.emptyframeplain && echo done

(( `wc -l $file.$frame.emptyframeplain | awk '{print $1}'` != 4 )) && \
        echo Error: too much lines in $file.$frame.emptyframeplain && exit 1

