#!/bin/bash

. ./feedcrack.lib.bash

[[ -z $2 ]] && usage

file=$1
frame=$2

burst() {
	burst2=$(( $frame + 1 ))
	burst3=$(( $frame + 2 ))
	burst4=$(( $frame + 3 ))
	grep "^$frame "  $file
	grep "^$burst2 " $file
	grep "^$burst3 " $file
	grep "^$burst4 " $file
	unset burst2 burst3 burst4
}

burst > $file.$frame.emptyframeplain && echo $file.$frame.emptyframeplain

