#!/bin/bash
set -e

utilspath=/root/KRAKEN/kraken/Utilities

[[ -z $3 ]] && echo XORED-BITSTRING AND XOR-FILE-1234? && exit 1

bitstring=$1
prefix1234=$2
cipherframes=$3

[[ ! -f $prefix1234 ]] && echo file $prefix1234 not found && exit 1

line=`sed -n "/$bitstring/=" $prefix1234`
echo xor found on line $line
echo

previousline=$(($line - 1))
echo corresponding enciphered bitstrings lines $previousline and $line
sed -n "$previousline,${line}p" $cipherframes
echo

framecount=`sed -n "${line}p"		$cipherframes | awk '{print $2}' | sed 's/:$//'`
framecount2=`sed -n "${previousline}p"	$cipherframes | awk '{print $2}' | sed 's/:$//'`

burst2=`sed -n "${previousline}p" $prefix1234`
echo xored burst2 for line $previousline
echo $burst2
echo

echo command line template
echo $utilspath/find_kc FOUND-KEY BIT-POSITION $framecount $framecount2 $burst2
echo

