#!/bin/bash
set -e

utilspath=/root/KRAKEN/kraken/Utilities

usage() {
	echo 'usage: $0 <xored bitstring> <prefix1234 file>'
	exit 1
}

[[ -z $2 ]] && usage

bitstring=$1
prefix1234=$2

[[ ! -f $prefix1234 ]] && echo file $prefix1234 not found && exit 1

line=`sed -n "/$bitstring/=" $prefix1234`
echo xor found on line $line
echo

previousline=$(($line - 1))
echo corresponding enciphered bitstrings lines $previousline and $line
sed -n "$previousline,${line}p" ${prefix1234%1234}cipher
echo

framecount=`sed -n "${line}p"		${prefix1234%1234}cipher | awk '{print $2}' | sed 's/:$//'`
framecount2=`sed -n "${previousline}p"	${prefix1234%1234}cipher | awk '{print $2}' | sed 's/:$//'`

burst2=`sed -n "${previousline}p" $prefix1234`
echo xored burst2 for line $previousline
echo $burst2
echo

echo command line template
echo $utilspath/find_kc FOUND-KEY BIT-POSITION $framecount $framecount2 $burst2
echo

