#!/bin/bash
set -e

[[ -z $1 ]] && echo ARFCN? && exit 1

arfcn=$1
cfile=/root/capture/$arfcn.cfile

echo "what pattern are you looking for exactly as for circuit switched IAs?"
echo -n "enter three bytes in HEX (e.g. 00:00:00) "
read circuit

	#"Time Slot:" \
	#"Sub-Slot:" \

tmp=`tshark -2 -R "gsm_a.dtap.msg_rr_type==0x3f && \
	frame[62:3] == $circuit" -r $cfile.0C.pcap -T text -V`
for pattern in \
	"GSM Frame Number:" \
	"Channel Description" \
	"Subchannel:" \
	"Timeslot:" \
	"Training Sequence:" \
	"Hopping Channel:" \
	"Spare:" \
	"Single channel ARFCN:" \
	"Timing advance value:" \
	; do
	echo "$tmp" | grep "$pattern"
done | uniq; unset pattern

