#!/bin/bash
set -e

[[ -z $3 ]] && echo ARFCN TIMESLOT SUBCHANNEL? && exit 1

arfcn=$1
slot=$2
sub=$3
cfile=/root/capture/$arfcn.cfile

	#"Time Slot:" \
	#"Sub-Slot:" \

echo func=UI
tmp=`tshark -2 -R "lapdm.control_field == 0x03 && \
	lapdm.control_field == 0x03 && \
	lapdm.length_field == 0x01 && \
	gsmtap.sub_slot == $sub" -r $cfile.${slot}S.pcap -T text -V`
for pattern in \
	"GSM Frame Number:" \
	; do
	echo "$tmp" | grep "$pattern"
done | uniq; unset pattern
unset tmp
echo

echo SI5
tmp=`tshark -2 -R "gsm_a.dtap.msg_rr_type == 0x1d &&
        gsmtap.sub_slot == $sub" -r $cfile.${slot}S.pcap -T text -V`
for pattern in \
        "GSM Frame Number:" \
        "Message Type:" \
        ; do
        echo "$tmp" | grep "$pattern"
done | uniq; unset pattern
unset tmp
echo

echo CMC
tmp=`tshark -2 -R "gsm_a.dtap.msg_rr_type == 0x35 && \
	gsmtap.sub_slot == $sub" -r $cfile.${slot}S.pcap -T text -V`
for pattern in \
        "GSM Frame Number:" \
        "Algorithm identifier:" \
        ; do
        echo "$tmp" | grep "$pattern"
done | uniq; unset pattern
unset tmp
echo

