#!/bin/bash

usage() {
	cat <<EOF

usage: <cfile> <arfcn> <timeslot>

EOF
	exit 1
}

[[ -z $3 ]] && usage

cfile=$1
arfcn=$2
slot=$3

#overrides ok
tcpdump -i lo -w $cfile.${slot}S.pcap &
grgsm_decode -a $arfcn -c $cfile -m SDCCH8 -t $slot
sleep 0.5
pkill tcpdump && echo tcpdump killed ok

echo -n json for SDCCH/8 timeslot $slot...
tshark -2 -R '!icmp && gsmtap' -r $cfile.${slot}S.pcap -T json > $cfile.${slot}S.json \
	&& echo $cfile.${slot}S.json && ln -sf $cfile.${slot}S.json mega2 && ls -lhF mega2

echo -m bit strings for SDCCH/8 timeslot $slot...
grgsm_decode -a $arfcn -c $cfile -m SDCCH8 -t ${slot} -p > $cfile.${slot}S \
	&& echo $cfile.${slot}S

