#!/bin/bash

receiver=/path/to/airprobe/gsm-receiver/src/python
arfcn=70
cfile=/path/to/arfcn.cfile

#overrides ok
tcpdump -i lo -w $cfile.0C.pcap &
grgsm_decode -a $arfcn -c $cfile -m BCCH -t 0
sleep 0.5
pkill tcpdump && echo tcpdump killed ok
tshark -2 -R '!icmp && gsmtap' -r $cfile.0C.pcap -T json \
	> $cfile.0C.pcap.json && echo $cfile.0C.pcap.json

slot=1

#overrides ok
tcpdump -i lo -w $cfile.${slot}S.pcap &
grgsm_decode -a $arfcn -c $cfile -m SDCCH8 -t $slot
sleep 0.5
pkill tcpdump && echo tcpdump killed ok
tshark -2 -R '!icmp && gsmtap' -r $cfile.${slot}S.pcap -T json \
	> $cfile.${slot}S.pcap.json && echo $cfile.${slot}S.pcap.json

cd $receiver/
./go.sh $cfile 64 ${slot}S &> $cfile.${slot}S_ && echo $cfile.${slot}S

