#!/bin/bash
set -e

usage() {
	echo "usage: $0 <cfile> <arfcn>"
	exit 1
}

[[ -z $2 ]] && usage

cfile=$1
arfcn=$2

echo writing to $cfile.0C.pcap
#overrides ok
tcpdump -i lo -w $cfile.0C.pcap &
grgsm_decode -a $arfcn -c $cfile -m BCCH -t 0
sleep 0.5
pkill tcpdump && echo tcpdump killed ok

echo -n writing BCCH timeslot 0 to $cfile.0C.txt...
tshark -2 -R '!icmp && gsmtap' -r $cfile.0C.pcap -T text -V \
	        > $cfile.0C.text 2>/dev/null && echo done

grep -i hopping $cfile.0C.text | sort -u

echo -n writing BCCH timeslot 0 to $cfile.0C.json ...
tshark -2 -R '!icmp && gsmtap' -r $cfile.0C.pcap -T json \
	> $cfile.0C.json 2>/dev/null && echo done

