#!/bin/bash
set -e

[[ -z $1 ]] && echo ARFCN? && exit 1

arfcn=$1
cfile=/root/capture/$arfcn.cfile

echo writing to $cfile.0C.pcap
#overrides ok
tcpdump -i lo -w $cfile.0C.pcap &
grgsm_decode -a $arfcn -c $cfile -m BCCH -t 0
sleep 0.5
pkill tcpdump && echo tcpdump killed ok

echo -n writing BCCH timeslot 0 to $cfile.0C.text ...
tshark -2 -R '!icmp && gsmtap' -r $cfile.0C.pcap -T text -V \
	        > $cfile.0C.text 2>/dev/null && echo done

echo hopping
grep -i hopping $cfile.0C.text | sort -u
echo neighbors and hopping friends
grep 'List of ARFCNs' $cfile.0C.text | sort -u
echo hopping bitmap
grep -i bitmap $cfile.0C.text | sort -u

echo -n writing BCCH timeslot 0 to $cfile.0C.json ...
tshark -2 -R '!icmp && gsmtap' -r $cfile.0C.pcap -T json \
	> $cfile.0C.json 2>/dev/null && echo done

