#!/bin/bash
set -e

[[ -z $2 ]] && echo ARFCN AND TIMESLOT? && exit 1

arfcn=$1
slot=$2
cfile=/root/capture/$arfcn.cfile

echo writing to $cfile.${slot}S.pcap
#overrides ok
tcpdump -i lo -w $cfile.${slot}S.pcap &
grgsm_decode -a $arfcn -c $cfile -m SDCCH8 -t $slot --print-bursts > $cfile.${slot}S
sleep 0.5
pkill tcpdump && echo tcpdump killed ok

echo burst bitstring file
ls -lhF $cfile.${slot}S

echo -n "writing SDCCH/8 timeslot $slot to $cfile.${slot}S.text ... "
tshark -2 -R '!icmp && gsmtap' -r $cfile.${slot}S.pcap -T text -V \
	> $cfile.${slot}S.text 2>/dev/null && echo done

echo ciphering
grep 'Ciphering Mode Command' $cfile.${slot}S.text | sort -u

echo -n "writing SDCCH/8 timeslot $slot to $cfile.${slot}S.json ... "
tshark -2 -R '!icmp && gsmtap' -r $cfile.${slot}S.pcap -T json \
	> $cfile.${slot}S.json 2>/dev/null && echo done

#Produce the burst bitstrings with frame references (it's already there)
#./bitstringsXS $cfile $arfcn $slot

